### ISSUE TITLE
Runner fails with "RuntimeError: Failed to create test command"

### ISSUE THREAD

**Issue by Benrnz** [bitrise-steplib/steps-nunit-runner#4]
I've been unable to get the NUnit runner to work with even the simplest of projects.  I've created a simple repo here to reproduce this issue:
https://github.com/Benrnz/BitriseNUnitTest

The unit test project only consists of a single test with Assert.True(true). The unit test project is set to target .NET 4.5.

I'm building in iPhone/Adhoc config.

```
+------------------------------------------------------------------------------+
| (7) nunit-runner@0.9.1                                                       |
+------------------------------------------------------------------------------+
| id: nunit-runner                                                             |
| version: 0.9.1                                                               |
| collection: https://github.com/bitrise-io/bitrise-steplib.git                |
| time: 2016-05-24T03:31:19-07:00                                              |
+------------------------------------------------------------------------------+
|                                                                              |

========== Configs ==========
 * solution: App1/App1.sln
 * configuration: Ad-Hoc
 * platform: iPhone

["\"/Applications/Xamarin Studio.app/Contents/MacOS/mdtool\"", "build", "\"-c:Ad-Hoc|iPhone\"", "\"App1/App1.sln\""]

Xamarin Studio Build Tool
Loading solution: /Users/vagrant/git/App1/App1.sln
   Loading solution: /Users/vagrant/git/App1/App1.sln
      Loading projects ..
Building Solution: App1 (Ad-Hoc|iPhone)
   Building: App1 (Release)
   Building: App1.Droid (Release)
   Building: UnitTest (Release)
#<RuntimeError: Failed to create test command>
--- Stack trace: ---
["/private/var/folders/lb/8n5bn9k975qgw662jpqdy7mm0000gn/T/bitrise518250445/step_src/xamarin-builder/builder.rb:76:in `run_nunit_tests'", "/var/folders/lb/8n5bn9k975qgw662jpqdy7mm0000gn/T/bitrise518250445/step_src/step.rb:72:in `<main>'"]
|                                                                              |
+----+--------------------------------------------------------------+----------+
| 🚫  | nunit-runner@0.9.1 (exit code: 1)                            | 16 sec   |
+----+--------------------------------------------------------------+----------+
| Issue tracker: https://github.com/bitrise-steplib/steps-nunit-runner/issues  |
| Source: https://github.com/bitrise-steplib/steps-nunit-runner                |
+----+--------------------------------------------------------------+----------+
```

**Comment by godrei** [comment]
Hi @Benrnz ,
thanks for reporting.

This [line](https://github.com/bitrise-steplib/steps-nunit-runner/blob/master/xamarin-builder/analyzer.rb#L58) cased the issue.
We use that regexp to deteremin if project is a nunit test project or not, but it does not find `nunit.framework` if version is present also.

Works for: `<Reference Include="nunit.framework">`
does not work for: `<Reference Include="nunit.framework, Version=2.6.4.14350, Culture=neutral, PublicKeyToken=96d09a1eb7f44a77, processorArchitecture=MSIL">`

Fix will come in the next release tomorrow.

**Comment by godrei** [comment]
Hi @Benrnz ,
new version ([v0.9.2](https://github.com/bitrise-steplib/steps-nunit-runner/releases/tag/0.9.2)) is out.
